#application.yml
 
server:
  port: 8086

logging:
  level:
    org.springframework.web: DEBUG,CONSOLE
  config: classpath:logback-boot.xml

spring:
  #多数据源 1主2从
  datasource:
   #从库数量
    readSize: 2
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  #主库
    master:
      url: jdbc:mysql://120.79.237.138:3306/master?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1Q2w3e4r!
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQueryTimeout: 900000
      validationQuery: SELECT SYSDATE() from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    slave1:
      url: jdbc:mysql://129.28.67.193:3306/slave1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Q1w2e3r4!
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQueryTimeout: 900000
      validationQuery: SELECT SYSDATE() from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    slave2:
      url: jdbc:mysql://120.79.237.138:3306/slave2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 1Q2w3e4r!
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQueryTimeout: 900000
      validationQuery: SELECT SYSDATE() from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strateg: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
